"""Writing figures, tables and reports to disk.

PDF and SVG keep their text as real text (``pdf.fonttype = 42``,
``svg.fonttype = "none"`` are set by :func:`somtrack.viz.style.apply_style`), so
labels can be restyled in Illustrator or Inkscape without re-running anything.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

import pandas as pd
from matplotlib import pyplot as plt

from .config import AnalysisConfig, ExportConfig
from .viz.style import Panel


@dataclass
class ExportManifest:
    out_dir: Path
    figures: dict[str, list[str]] = field(default_factory=dict)
    tables: list[str] = field(default_factory=list)
    videos: list[str] = field(default_factory=list)
    started: str = field(default_factory=lambda: datetime.now().isoformat(timespec="seconds"))

    def write(self) -> Path:
        path = self.out_dir / "manifest.json"
        path.write_text(json.dumps({
            "generated": self.started,
            "figures": self.figures,
            "tables": self.tables,
            "videos": self.videos,
        }, indent=2), encoding="utf-8")
        return path


def save_panel(panel: Panel, name: str, cfg: ExportConfig,
               manifest: ExportManifest | None = None,
               close: bool = True) -> list[Path]:
    """Write one figure in every enabled format."""
    out = Path(cfg.out_dir) / "figures"
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    fmts = []
    if cfg.png:
        fmts.append(("png", {"dpi": cfg.dpi_png if hasattr(cfg, "dpi_png") else 600}))
    if cfg.pdf:
        fmts.append(("pdf", {}))
    if cfg.svg:
        fmts.append(("svg", {}))

    for ext, kw in fmts:
        path = out / f"{name}.{ext}"
        panel.fig.savefig(path, format=ext, facecolor="white", **kw)
        written.append(path)

    if manifest is not None:
        manifest.figures[name] = [str(p) for p in written]
    if close:
        plt.close(panel.fig)
    return written


def save_multipage_pdf(panels: list[tuple[str, Panel]], path: str | Path,
                       close: bool = True) -> Path:
    """One editable-text PDF holding the whole figure set, in order."""
    from matplotlib.backends.backend_pdf import PdfPages

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with PdfPages(path) as pdf:
        meta = pdf.infodict()
        meta["Title"] = "SOMTrack analysis report"
        meta["Creator"] = "SOMTrack"
        meta["CreationDate"] = datetime.now()
        for _, panel in panels:
            pdf.savefig(panel.fig, facecolor="white")
    if close:
        for _, panel in panels:
            plt.close(panel.fig)
    return path


def save_table(df: pd.DataFrame, name: str, cfg: ExportConfig,
               manifest: ExportManifest | None = None) -> Path:
    out = Path(cfg.out_dir) / "tables"
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{name}.csv"
    df.to_csv(path, index=False, encoding="utf-8-sig")
    if manifest is not None:
        manifest.tables.append(str(path))
    return path


def save_tables_workbook(tables: dict[str, pd.DataFrame], path: str | Path) -> Path:
    """All result tables as one multi-sheet .xlsx."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(path, engine="openpyxl") as xl:
        for name, df in tables.items():
            df.to_excel(xl, sheet_name=name[:31], index=False)
    return path


def save_config(config: AnalysisConfig, cfg: ExportConfig) -> Path:
    out = Path(cfg.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    return config.to_json(out / "analysis_config.json")


def write_methods_text(path: str | Path, config: AnalysisConfig,
                       quality: dict, prep_notes: list[str],
                       n_samples: int, n_features: int,
                       n_groups: int, som_shape: tuple[int, int]) -> Path:
    """A methods paragraph with the actual parameters used, ready to paste."""
    som = config.som
    pre = config.preprocess
    lines = [
        "Methods (auto-generated by SOMTrack)",
        "=" * 60,
        "",
        f"{n_samples} tracks from {n_groups} experimental groups were described by "
        f"{n_features} locomotion metrics. "
        f"Features were scaled with the {pre.scaler} transform"
        + (f", pruning collinear metrics at |r| > {pre.collinearity_threshold:g}"
           if 0 < pre.collinearity_threshold < 1 else "")
        + f"; missing values were handled by '{pre.nan_policy}'.",
        "",
        f"A {som_shape[0]} x {som_shape[1]} {som.topology}agonal self-organising map"
        + (" with toroidal boundary conditions" if som.toroidal else "")
        + f" was trained for {som.epochs} epochs using the {som.algorithm} algorithm, "
        f"initialised from the first two principal components"
        if som.init == "pca" else
        f"initialised at {som.init}",
    ]
    lines[-1] += (
        f". The neighbourhood radius decayed exponentially from "
        f"{som.sigma0 if som.sigma0 > 0 else max(som_shape) / 2:.2f} to "
        f"{som.sigma_final:g} node widths with a time constant of "
        f"{som.time_constant:g} of the run length."
    )
    if som.algorithm == "supervised":
        lines.append(
            f"Group identity was carried as a fused label block with weight "
            f"alpha = {som.label_weight:g} (XY-fused SOM; Melssen et al. 2006)."
        )
    if som.algorithm == "relevance":
        lines.append(
            f"Feature relevances were learned by GRLVQ (learning rate "
            f"{som.relevance_lr:g}, floor {som.relevance_floor:g})."
        )
    lines += [
        "",
        "Map quality: " + ", ".join(f"{k.replace('_', ' ')} = {v:.3f}"
                                    for k, v in quality.items()
                                    if isinstance(v, (int, float))),
        "",
    ]
    if prep_notes:
        lines += ["Preprocessing notes:"] + [f"  - {n}" for n in prep_notes] + [""]

    lines += [
        "Figures were produced with matplotlib; PDF and SVG output embeds text as "
        "editable text (TrueType, fonttype 42).",
        "",
    ]
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


__all__ = [
    "ExportManifest", "save_panel", "save_multipage_pdf", "save_table",
    "save_tables_workbook", "save_config", "write_methods_text",
]
